name: CI
# Trigger the workflow on push to any branch except main
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  # build test name of status that is set to green or red depending on if tests succeed
  # used for pr merging rules and requests
  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
     - name: Build and Run Tests
         working-directory: ./GothicLlamasAPI
        run: mvn clean test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - run: echo "This job's status is ${{ job.status }}."